[package]
name = "bevy_message_window"
version = "0.0.1"
edition = "2021"
workspace = "../../bevy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ab_glyph = "0.2.21"
serde = "1.0.163"
nom = "7.1.3"

#bevy
bevy = { path = "../../bevy", version = "0.11.0-dev" }
